### ISSUE TITLE
Sin colocar mi nombre, me da inicio a la trivia 

### ISSUE THREAD

**Issue by emilyalvae** [Carol2Paola/Trivia-Carol-Garcia2#2]
Cuando pide ingresar mi nombre y no lo hago, con solo darle enter puedo participar en la trivia.

![nombre](https://user-images.githubusercontent.com/113310590/190839623-f1bfc5f0-c1c5-43f3-a07a-8635e49d7d9d.png)

**Comment by Carol2Paola** [comment]
Tienes razón! Se va corregir.
